### ISSUE TITLE
Getting the exact (necessary) word count and removing error stemming from the same.

### ISSUE THREAD

**Issue by aymuos15** [cai4cai/XCLThesisTemplate#5]
![Screenshot-9](https://github.com/user-attachments/assets/405cea4d-0958-4d13-beda-fdbcd8530ade)

Any way to get the exact word count and remove the error shown in the picture?

**Comment by tvercaut** [comment]
Please make sure you provide more context to your issues. I assume this is a screenshot from an error message in overleaf. 
Anyway, this does not seem to be an issue with the template but rather with the `texcount` utility that overleaf uses under the hood. I have now posted a question about it on SO:
https://tex.stackexchange.com/questions/729378/texcount-error-with-biblatex-declarecitecommand

**Comment by aymuos15** [comment]
Thank you very much -- Have gone through the stack answer.

Will make sure to provide better context next time.
